<a href="https://colab.research.google.com/github/artlines/math_matrix/blob/master/%D0%91%D0%B0%D0%B7%D0%BE%D0%B2%D0%B0%D1%8F_%D0%BC%D0%B0%D1%82%D0%B5%D0%BC%D0%B0%D1%82%D0%B8%D0%BA%D0%B0_%D0%97%D0%B0%D0%BD%D1%8F%D1%82%D0%B8%D0%B5_1_%D0%9C%D0%B0%D1%82%D1%80%D0%B8%D1%86%D1%8B.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Курс "Базовая математика"
#Занятие 1. Матрицы
##Скаляры, векторы и матрицы

![alt text](https://drive.google.com/uc?id=1SdVkELm59y1FN4Sd8YDMI93W9HP10LZ-)


In [0]:
import numpy as np

In [0]:
scalar1 = 1
scalar2 = 5
scalar3 = 17.345
scalar4 = -3.2476

print('Скаляры')
print(scalar1)
print(scalar2)
print(scalar3)
print(scalar4)

Скаляры
1
5
17.345
-3.2476


In [0]:
vector = np.array([1.3, 4.2, -2.2, 13.1])
vector_vertical = np.array([1.3, 4.2, -2.2, 13.1]).reshape((4,1))

print('Горизонтальный вектор:', vector)

print('Вертикальный вектор:\n', vector_vertical)

Горизонтальный вектор: [ 1.3  4.2 -2.2 13.1]
Вертикальный вектор:
 [[ 1.3]
 [ 4.2]
 [-2.2]
 [13.1]]


In [0]:
print(vector.shape)
print(vector_vertical.shape)

(4,)
(4, 1)


In [0]:
def print_vector(v):
  shape = v.shape
  
  if (len(shape) == 0):
    print(v)
    
  if (len(shape) == 1):
    s = ''
    for i in v:
      s += str(i) + '  '
    print(s)
      
  if (len(shape) == 2):
    for i in range(shape[0]):
      s = ''
      for j in range(shape[1]):
        s += str(v[i][j]) + '  '
      print(s)

In [0]:
print_vector(vector)

1.3  4.2  -2.2  13.1  


In [0]:
print_vector(vector_vertical)

1.3  
4.2  
-2.2  
13.1  


##Операции с векторами

###Операции вектор - скаляр
![alt text](https://drive.google.com/uc?id=1xg5AnOyZpFiGniGeaH3UubiLH5jLrLKb)

**Добавление и вычитание скаляра**

In [0]:
print_vector(vector)
print_vector(vector + 1)
print_vector(vector - 2)

1.3  4.2  -2.2  13.1  
2.3  5.2  -1.2000000000000002  14.1  
-0.7  2.2  -4.2  11.1  


**Умножение на скаляр**

In [0]:
print_vector(vector * 2)

2.6  8.4  -4.4  26.2  


**Деление на скаляр**

In [0]:
print_vector(vector / 4)

0.325  1.05  -0.55  3.275  


**Возведение в степень**

In [0]:
print_vector(vector ** 2)

1.6900000000000002  17.64  4.840000000000001  171.60999999999999  


###Операции вектор-вектор
![link text](https://drive.google.com/uc?id=1qZzN-UnUTVRDX_OG3WZPawtbDFAFI3Nf)


**Сложение и вычитание векторов**

In [0]:
vector1 = np.array([0, 1, 2, 3])
vector2 = np.array([1, 2, 3, 4])

In [0]:
print_vector(vector1 + vector2)

1  3  5  7  


In [0]:
print_vector(vector1 - vector2)

-1  -1  -1  -1  


**Умножение и деление векторов**

In [0]:
print_vector(vector1 * vector2)

0  2  6  12  


In [0]:
print_vector(vector1 / vector2)

0.0  0.5  0.6666666666666666  0.75  


**Возведение в степень**

In [0]:
print_vector(vector1 ** vector2)

0  1  8  81  


#Матрицы

##Пример матрицы

In [0]:
matrix = np.array([[0, 1, 2], [1, 2, 3], [2, 3, 4]])

NameError: ignored

In [0]:
print_vector(matrix)

NameError: ignored

##Цикл по матрице
Для примера, найдём максимум матрицы

In [0]:
matrix2 = np.array([[145, 23, 191], [17, 252, 31], [99, 112, 39]])
print_vector(matrix2)

145  23  191  
17  252  31  
99  112  39  


In [0]:
matrix_max = 0

for i in range(matrix2.shape[0]):
  for j in range(matrix2.shape[1]):
    if (matrix2[i,j] > matrix_max):
      matrix_max = matrix2[i,j]

print('Максимум матрицы =', matrix_max)

Максимум матрицы = 252


##Операции с матрицами

###Операции матрица - скаляр
- добавление
- вычитание
- умножение
- деление
- возведение в степень
![link text](https://drive.google.com/uc?id=1oLRLWVMl2lTZXutpCg_VXhRKrPOqlO_V)

In [0]:
print('Добавление')
print_vector(matrix + 1)

print()
print('Умножение')
print_vector(matrix * 2)

print()
print('Деление')
print_vector(matrix / 4)

print()
print('Возведение в степень')
print_vector(matrix ** 2)

Добавление
1  2  3  
2  3  4  
3  4  5  

Умножение
0  2  4  
2  4  6  
4  6  8  

Деление
0.0  0.25  0.5  
0.25  0.5  0.75  
0.5  0.75  1.0  

Возведение в степень
0  1  4  
1  4  9  
4  9  16  


###Поэлементные операции с матрицами
![link text](https://drive.google.com/uc?id=1MzSTEzCgi7e89ZrYeTKoxtf7HWYOb3a1)

In [0]:
print('Добавление')
print_vector(matrix + matrix2)

print()
print('Умножение')
print_vector(matrix * matrix2)

print()
print('Деление')
print_vector(matrix / matrix2)

print()
print('Возведение в степень')
print_vector(matrix2 ** matrix)

Добавление
145  24  193  
18  254  34  
101  115  43  

Умножение
0  23  382  
17  504  93  
198  336  156  

Деление
0.0  0.043478260869565216  0.010471204188481676  
0.058823529411764705  0.007936507936507936  0.0967741935483871  
0.020202020202020204  0.026785714285714284  0.10256410256410256  

Возведение в степень
1  23  36481  
17  63504  29791  
9801  1404928  2313441  


###Умножение матриц
Ячейка i, j новой матрицы равна сумме умножения по элементам
- строки i первой матрицы
- колонки j второй матрицы
![alt text](https://drive.google.com/uc?id=1a4NtU-kJzjpXyJOcDW0eeB7vOpR9H9aC)

In [0]:
def prod_matrix(matrix1, matrix2):
  shape1 = matrix1.shape
  shape2 = matrix2.shape
  
  if (shape1[1] != shape2[0]):
    return np.array([])
  
  out_matrix = np.zeros((shape1[0], shape2[1]))
  
  for i in range(shape1[0]):
    for j in range(shape2[1]):
      curr_cell = 0
      for t in range(shape1[1]):
        curr_cell += matrix1[i,t] * matrix2[t,j]
        out_matrix[i,j] = curr_cell
  
  return out_matrix

In [0]:
matrix1 = np.array([[0, 1, 2], [1, 2, 3], [2, 3, 4], [3, 4, 5]])
matrix2 = np.array([[0, 1, 2, 3], [1, 2, 3, 4], [2, 3, 4, 5]])

print_vector(matrix1)
print()
print_vector(matrix2)

0  1  2  
1  2  3  
2  3  4  
3  4  5  

0  1  2  3  
1  2  3  4  
2  3  4  5  


In [0]:
matrix3 = prod_matrix(matrix1, matrix2)
print_vector(matrix3)

5.0  8.0  11.0  14.0  
8.0  14.0  20.0  26.0  
11.0  20.0  29.0  38.0  
14.0  26.0  38.0  50.0  


###Умножение векторов в матрицу
![link text](https://drive.google.com/uc?id=1TgzDXjnovEEeSTt7BjoWT6S77IP3ZDF2)

In [0]:
vector1 = np.array([1, 2, 3, 4]).reshape((1,4))
vector2 = np.array([5, 4, 3]).reshape((3,1))

print('Первый вектор')
print_vector(vector1)
print()
print('Второй вектор')
print_vector(vector2)


matrix4 = prod_matrix(vector2, vector1)

print()
print('Итоговая матрица')
print_vector(matrix4)

print()
print('Првоерка размерности')
print(vector2.shape)
print(vector1.shape)
print(matrix4.shape)

Первый вектор
1  2  3  4  

Второй вектор
5  
4  
3  

Итоговая матрица
5.0  10.0  15.0  20.0  
4.0  8.0  12.0  16.0  
3.0  6.0  9.0  12.0  

Првоерка размерности
(3, 1)
(1, 4)
(3, 4)


###Умножение матрицы на вектор
![link text](https://drive.google.com/uc?id=19-qTGxHbUe6l96XVA5fiMOwwNHb8VT8D)

![link text](https://drive.google.com/uc?id=1VJNpv1hmvjqqE03tR7WQFSBnAykC3gDK)

###Транспонирование матриц
![link text](https://drive.google.com/uc?id=1vgodAPexaLD_FRNYuwrK7Pl2Lx9uK82z)

In [0]:
def transpose_matrix(matrix):
  shape = matrix.shape
  
  out_matrix = np.zeros((shape[1], shape[0]))
  
  for i in range(shape[0]):
    for j in range(shape[1]):
      out_matrix[j,i] = matrix[i,j]
  
  return out_matrix

In [0]:
transpose_matrix = transpose_matrix(matrix1)

print('Оригинальная матрица')
print_vector(matrix1)

print()
print('Транспонированная матрица')
print_vector(transpose_matrix)

Оригинальная матрица
0  1  2  
1  2  3  
2  3  4  
3  4  5  

Транспонированная матрица
0.0  1.0  2.0  3.0  
1.0  2.0  3.0  4.0  
2.0  3.0  4.0  5.0  


###Обратные матрицы
Обратная матрица, это такая матрица, при умножении на которую, исходная матрица превратится в матрицу с 1 на диагонали и 0 в остальных ячейках
![link text](https://drive.google.com/uc?id=11cxOXWSLI_LqEK2LnyW8F5fQWgSRRccN)

In [0]:
matrix_4_inv = np.array([[4, 1, 3], [3, 5, 2], [2, 6, 4]])

In [0]:
inv_matrix = np.linalg.inv(matrix_4_inv)
print_vector(inv_matrix)

0.16666666666666669  0.29166666666666663  -0.2708333333333333  
-0.16666666666666669  0.20833333333333337  0.020833333333333322  
0.16666666666666669  -0.45833333333333337  0.3541666666666667  


In [0]:
result_matrix = prod_matrix(matrix_4_inv, inv_matrix)
print_vector(result_matrix)

1.0  0.0  0.0  
-1.1102230246251565e-16  1.0000000000000002  0.0  
1.1102230246251565e-16  0.0  1.0  


#Домашнее задание

**Задача 1**

Напишите функцию умножения трёх матриц

In [0]:
import numpy as np

matrix_1 = np.array([[0,1,2], [3,4,5], [6,7,8],[9,10,11]])
matrix_2 = np.array([[12,13,14, 15], [16,17,18,19], [16,17,18,19]])
matrix_3 = np.array([[20,21,22,23], [22,23,24,25], [22,23,24,25], [22,23,24,25]])

def multi_matrix_3(m1, m2, m3):
  sh1, sh2, sh3 = m1.shape, m2.shape, m3.shape
  if (sh1[1] != sh2[0]):
    return np.array([])

  tmp = multi_matrix(m1, m2)
  tmp_sh = tmp.shape
  print('Размерность матрицы, полученной при умножении m1 и m2', tmp_sh)
  print('Размерность матрицы m3', sh3)
  if(tmp_sh[1] != sh3[0]):
    return np.array([])

  result = multi_matrix(tmp, m3)

  return result
  
  

multi_matrix_3(matrix_1, matrix_2, matrix_3)


Размерности матриц:  (4, 3) (3, 4)
Размерность матрицы, полученной при умножении m1 и m2 (4, 4)
Размерность матрицы m3 (4, 4)
Размерности матриц:  (4, 4) (4, 4)


array([[ 4524.,  4734.,  4944.,  5154.],
       [17064., 17856., 18648., 19440.],
       [29604., 30978., 32352., 33726.],
       [42144., 44100., 46056., 48012.]])

**Задача 2**

Напишите функцию, которая считает разницу между максимальным и минимальным элементами матрицы

In [0]:
import numpy as np

matrix = np.array([[2,1,2], [3,4,5], [6,7,8],[9,10,20]])


def min_max_diff(matrix):
  minimum, maximum = matrix[0, 0], matrix[0, 0]
  shape = matrix.shape
  for i in range(shape[0]):
    for j in range(shape[1]):
      minimun = matrix[i,j] if matrix[i,j] < minimum else minimum
      maximum = matrix[i,j] if matrix[i,j] > maximum else maximum

  return maximum - minimum


print(min_max_diff(matrix))

18


**Задача 3**

Напишите функцию, которая
- умножает матрицу на саму себя, но транспонированную
- берёт обратную матрицу от результата

In [0]:
import numpy as np

matrix1 = np.array([[2,1,2], [3,4,5], [6,7,8],[9,10,20]])
matrix2 = np.array([[2,1,2,1], [3,4,5,1], [6,7,8,1]])


def back_matrix(matrix):
  print('Исходная матрица \n', matrix)
  
  transposed = transpose_matrix(matrix)
  print('Транспонированная матрица \n', transposed)
  
  multi = multi_matrix(matrix, transposed)
  print('Произведение матриц \n', multi)
  
  back = np.linalg.pinv(multi)
  print('Обратная матрица от результата \n', back)


def transpose_matrix(matrix):
  shape = matrix.shape
  transposed = np.zeros((shape[1], shape[0]))
  for i in range(shape[0]):
    for j in range(shape[1]):
      transposed[j,i] = matrix[i, j]

  return transposed


def multi_matrix(m1, m2):
  sh1 = m1.shape
  sh2 = m2.shape
  print('Размерности матриц: ', sh1, sh2)
  if (sh1[1] != sh2[0]):
    return np.array([])

  nova_matrix = np.zeros((sh1[0], sh2[1]))
  for i in range(sh1[0]):
    for j in range(sh2[1]):
      tmp = 0
      for t in range(sh1[1]):
        tmp +=m1[i,t] * m2[t,j] 
        nova_matrix[i,j] = tmp
  
  return nova_matrix

back_matrix(matrix1)


Исходная матрица 
 [[ 2  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 20]]
Транспонированная матрица 
 [[ 2.  3.  6.  9.]
 [ 1.  4.  7. 10.]
 [ 2.  5.  8. 20.]]
Размерности матриц:  (4, 3) (3, 4)
Произведение матриц 
 [[  9.  20.  35.  68.]
 [ 20.  50.  86. 167.]
 [ 35.  86. 149. 284.]
 [ 68. 167. 284. 581.]]
Обратная матрица от результата 
 [[ 0.99850662 -0.40268431  0.01293636 -0.00739761]
 [-0.40268431  0.17604705  0.02550305 -0.01582861]
 [ 0.01293636  0.02550305  0.06937408 -0.04281033]
 [-0.00739761 -0.01582861 -0.04281033  0.02805293]]
